[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
frunk.workspace = true
frunk_core.workspace = true
frunk_utils.workspace = true
frunk_utils_derives.workspace = true
ndarray.workspace = true

generic_lib = { path = "../generic_lib" }
